### PR TITLE
[TCOTD2] Added a poison mechanic

### PR DESCRIPTION
**Pull request by Blue-Shadow**
When poisoned, the player slowly loses health over time. The ailment reduces health to a minimum value of 1, so it doesn't, itself, kill the player. To heal from it, use an antidote.

### CODE REVIEW

**Comment by Tormentor667** [comment]
I like it but I wonder from what does the player get poisoned?

**Comment by Blue-Shadow** [comment]
> I wonder from what does the player get poisoned?

Only from the Vulgar's ranged attack, currently, and that's because it already had the capability to inflict poison damage (though it used a different poison mechanic, the [GZDoom built-in one](https://zdoom.org/wiki/Poison)).

**Comment by Tormentor667** [comment]
Considering the amount of the Vulgars around, I'd suggest adding this mechanic to a different enemy, so the player also has to explore the map for the antidote for a while as an additional gaming aspect. What do you think?

**Comment by Blue-Shadow** [comment]
The Vulgar is the most suitable. I mean, the small spiders aren't uncommon (not to mention, they're annoying as it is), while the big ones are only encountered in that boss fight. There's the butcher zombie with its bile attack, but would you consider that attack fitting for a poisonous one? I don't know...

The solution is to thin the number of the vulgars. The ones encountered outside of the city at the beginning of the game either need removing entirely or replacing (the ones in the swamp should probably be kept). In addition to that, I could make it so that poison isn't always inflicted each time the player is damaged by a poisonous attack. Instead, make it a random chance. Let's face it, this isn't Resident Evil, where poisonous monsters are uncommon, and even if you encounter them, it's just one or two.

**Comment by nashmuhandes** [comment]
It's a cool mechanic and idea, I like it.

Just as a coincidence - from the latest round of playtesting feedback, it was suggested that the Vulgar at the start is replaced with a melee monster too, it has to do with weapon pacing. Too early to frontload a projectile enemy right at the beginning.

**Comment by Tormentor667** [comment]
Yes, good point.

**Pull request merged**
